//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int user_id { get; set; }
        public string ma_sv { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string address { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
    }
}
